# Generated by Django 2.0.6 on 2018-07-15 01:30

import colorfield.fields
import colorful.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('webapp', '0001_initial'), ('webapp', '0002_auto_20180626_0351'), ('webapp', '0003_auto_20180626_0416'), ('webapp', '0004_auto_20180626_0428'), ('webapp', '0005_auto_20180626_0436'), ('webapp', '0006_auto_20180628_0849')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('current_streak', models.PositiveIntegerField()),
                ('longest_streak', models.PositiveIntegerField()),
                ('last_log_entry', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('achieved', 'Achieved')], max_length=20)),
                ('color', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('logged', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Habit')),
            ],
        ),
        migrations.AddField(
            model_name='habit',
            name='schedule',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='last_log_entry',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='habit',
            name='last_log_entry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='color',
            field=colorfield.fields.ColorField(default='#663399', max_length=18),
        ),
        migrations.AlterField(
            model_name='habit',
            name='color',
            field=colorfield.fields.ColorField(default='#663399', max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='color',
            field=colorful.fields.RGBColorField(default='#63399'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
