# Generated by Django 2.0.6 on 2018-06-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='schedule',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='habit',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habit',
            name='last_log_entry',
            field=models.DateTimeField(),
        ),
    ]
