# Generated by Django 2.0.6 on 2018-07-15 01:31

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_squashed_0006_auto_20180628_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='color',
            field=colorful.fields.RGBColorField(default='#663399'),
        ),
    ]
