# Generated by Django 2.0.6 on 2018-06-26 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20180626_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='last_log_entry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
