# Generated by Django 2.0.6 on 2018-06-26 04:36

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20180626_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='color',
            field=colorfield.fields.ColorField(default='#663399', max_length=18, null=True),
        ),
    ]
