# Generated by Django 2.0.6 on 2018-06-28 08:49

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180626_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='color',
            field=colorful.fields.RGBColorField(default='#63399'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
